gaps:
  inner_gap: 20
  outer_gap: 20

bar:
  height: 50
  position: "top"
  opacity: 0
  background: "#101010"
  foreground: "white"
  font_family: "Segoe UI"
  font_size: "13"
  padding: "1 6 1 6"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#8192B3"
      displayed_workspace_background: "#42403e"
      default_workspace_background: "#101010"
  components_right:
    - type: "clock"
      time_formatting: "hh:mm:ss  d ddd MMM"

workspaces:
  - name: 1
    display_name: "web"
  - name: 2
    display_name: "code"
  - name: 3
    display_name: "music"
  - name: 4
    display_name: "games"
  - name: 5
    display_name: "misc"
  - name: 6
    display_name: "chillzone 5 million"
  - name: 7
  - name: 8
  - name: 9

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running the WM as admin.
  - command: "ignore"
    match_process_name: "Taskmgr"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

keybindings:
  - command: "focus left"
    bindings: ["Control+Alt+A"]

  - command: "focus right"
    bindings: ["Control+Alt+T"]

  - command: "focus up"
    bindings: ["Control+Alt+S"]

  - command: "focus down"
    bindings: ["Control+Alt+R"]

  - command: "move left"
    bindings: ["Control+Alt+Shift+A"]

  - command: "move right"
    bindings: ["Control+Alt+Shift+T"]

  - command: "move up"
    bindings: ["Control+Alt+Shift+S"]

  - command: "move down"
    bindings: ["Control+Alt+Shift+R"]

  - command: "resize width -2%"
    binding: "Control+Alt+N"

  - command: "resize width +2%"
    binding: "Control+Alt+O"

  - command: "resize height +2%"
    binding: "Control+Alt+I"

  - command: "resize height -2%"
    binding: "Control+Alt+E"

  - command: "layout horizontal"
    binding: "Control+Alt+H"

  - command: "layout vertical"
    binding: "Control+Alt+V"

  - command: "toggle focus mode"
    binding: "Control+Alt+Space"

  - command: "toggle floating"
    binding: "Control+Alt+Shift+Space"

  - command: "close"
    binding: "Control+Alt+X"

  - command: "exit wm"
    binding: "Control+Alt+Z"

  - command: "focus workspace 1"
    binding: "Control+Alt+Q"

  - command: "focus workspace 2"
    binding: "Control+Alt+W"

  - command: "focus workspace 3"
    binding: "Control+Alt+F"

  - command: "focus workspace 4"
    binding: "Control+Alt+P"

  - command: "focus workspace 5"
    binding: "Control+Alt+B"

  - command: "focus workspace 6"
    binding: "Control+Alt+J"

  - command: "focus workspace 7"
    binding: "Control+Alt+L"

  - command: "focus workspace 8"
    binding: "Control+Alt+U"

  - command: "focus workspace 9"
    binding: "Control+Alt+Y"

  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Control+Alt+Shift+Q"

  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Control+Alt+Shift+W"

  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Control+Alt+Shift+F"

  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Control+Alt+Shift+P"

  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Control+Alt+Shift+B"

  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Control+Alt+Shift+J"

  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Control+Alt+Shift+L"

  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Control+Alt+Shift+U"

  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Control+Alt+Shift+Y"]
