[Variables]
Bar_Opacity=00
Bar_Width =3417
Bar_Height =50
Bar_OffsetX =0
Bar_OffsetY =0

Section_Height =40

Color_Scheme1 =B4E7DF
Color_Scheme2 =27263C
Color_Scheme3 =F6BB94
Color_Scheme4 =F18EAC
Color_Scheme5 =DDB6F2
Color_Scheme6 =D2D4FB
Color_Scheme7 =FAE3B0
Color_Scheme8 =302D41
Color_Scheme9 =ABE9B3



Font_Face1=Futura Bk BT
Font_Face2=FF DIN Round Pro
Font_Size=14

Shadow=0
Translucent=0
DefaultAddedModules=startmenu,music,workspacemanager,volume,weather,tray,date,time,power

